---
title: "Memorable Quotes"
output: rmdformats::readthedown
---

## Index
* [Home](index.html)

## 2020 Reads {.tabset .tabset-pills}


## 2021 Reads {.tabset .tabset-pills}


## 2022 Reads {.tabset .tabset-pills}
### Fiction
#### The Forever War, by Joe Haldeman
* The 1143-year-long war hand begun on false pretenses and only because the two races were unable to communicate. Once they could talk, the first question was 'Why did you start this thing?' and the answer was 'Me?

* Reality becomes illusory and observer-oriented when you study general relativity. Or Buddhism. Or get drafted.

* In the few moments I lay awake after finally lying down, the thought came to me that the next time I closed my eyes could well be the last. And partly because of the drug hangover, mostly because of the past day’s horrors, I found that I really didn’t give a shit.

* You couldn’t blame it all on the military, though. The evidence they presented for the Taurans’ having been responsible for the earlier casualties was laughably thin. The few people who pointed this out were ignored. The fact was, Earth’s economy needed a war, and this one was ideal. It gave a nice hole to throw buckets of money into, but would unify humanity rather than dividing it.

#### The Mountains Sing, by Nguyen Phan Que Mai
* Human lives were short and fragile. Time and illnesses consumed us, like flames burning away these pieces of wood. But it didn’t matter how long or short we lived. It mattered more how much light we were able to shed on those we loved and how many people we touched with our compassion.

* If our stories survive, we will not die, even when our bodies are no longer here on this Earth.

* History will write itself in people's memories, and as long as those memories live on, we can have faith that we can do better.

* Being a mother is never easy... It’s about failing, learning, and then failing again.

* The challenges faced by Vietnamese people throughout history are as tall as the tallest mountains. If you stand too close, you won't be able to see their peaks. Once you step away from the currents of life, you will have the full view...

#### Train Dreams, by Denis Johnson
* It was only when you left it alone that a tree might treat you as a friend. After the blade bit in, you had yourself a war.

* Living up the Moyea with plenty of small chores to distract him, he forgot he was a sad man. When the hymns began, he remembered.

* Animals had returned to what was left of the forest...clusters of orange butterflies exploded off the blackish purple piles of bear sign and winked and fluttered magically like leaves without trees. More bears than people traveled the muddy road, leaving tracks straight up and down the middle of it.

* Frost had built on the dead grass, and it skirled beneath his feet. If not for this sound he’d have thought himself struck deaf, owing to the magnitude of the surrounding silence. All the night’s noises had stopped. The whole valley seemed to reflect his shock. He heard only his footsteps and the wolf-girl’s panting complaint.

* Howling, are you?” the Indian said. “There it is for you, then. That’s what happens, that’s what they say: There’s not a wolf alive that can’t tame a man.

#### The Calculating Stars (Lady Astronaut Universe #1), by Mary Robinette Kowal
* It’s hard to convince people that catastrophic weather changes are coming on a nice day.

* Without a plane, what was I supposed to do? Math the problem to death?

* Even geniuses can be stupid when they’re scared.

#### Blackout (Oxford Time Travel #1), by Connie Willis
* I’m not studying the heroes who lead navies—and armies—and win wars. I’m studying ordinary people who you wouldn’t expect to be heroic, but who, when there’s a crisis, show extraordinary bravery and self-sacrifice. Like Jenna Geidel, who gave her life vaccinating people during the Pandemic. And the fishermen and retired boat owners and weekend sailors who rescued the British Army from Dunkirk. And Wells Crowther, the twenty-four-year-old equities trader who worked in the World Trade Center. When it was hit by terrorists, he could have gotten out, but instead he went back and saved ten people, and died. I’m going to observe six different sets of heroes in six different situations to try to determine what qualities they have in common.

* History was full of divergence points nobody could get anywhere near—from Archduke Ferdinand’s assassination to the battle of Trafalgar. Events so critical and so volatile that the introduction of a single variable—such as a time traveler—could change the outcome. And alter the entire course of history.

* That was the most difficult thing about time travel, remembering where and when one was. She’d forgotten she wasn’t still a servant and called Linna “ma’am” twice.

#### What Strange Paradise, by Omar El Akkad
* Every man you ever meet in nothing but the product of what was withheld from him, what he feels owed.

* The west you talk about doesn’t exist. It’s a fairytale, a fantasy you sell yourself because the alternative is to admit that you are the least important character in your own story. You invent an entire world because your conscience demands it, you invent good people and bad people and you draw a neat line between them because your simplistic morality demands it. But the two kinds of people in this world are not good and bad, they are engines and fuel. Go ahead, change your country, change your name, change your accent, pull the skin right off your bones, but in their eyes they will always be the engines and you will always, always be fuel.

* Today you are the only boy in the world and tomorrow it will be as though you never existed.

* He quickly learned you could tell the quality of a product by how Western the people on the packaging looked.

* Vanna could not help but think of ancestry as a kind of shackle one could never fully unclasp, an umbilical cord that, not matter how deeply cut, could never be severed.

* In their silent reticence was evident the reality that somewhere along the journey they'd passed the point where human goodness gave way to the calculus of survival.

#### All Clear (Oxford Time Travel #2), by Connie Willis
* But if she'd come then, she would never have properly appreciated it. She'd have seen the happy crowds and the Union Jacks and the bonfires, but she'd have no idea of what it meant to see the lights on after years of navigating in the dark, what it meant to look up at an approaching plane without fear, to hear church bells after years of air-raid sirens. She'd have had no idea of the years of rationing and shabby clothes and fear which lay behind the smiles and the cheering, no idea of what it had cost to bring this day to pass--the lives of all those soldiers and sailors and airmen and civilians.

* He looked resigned, as though he knew that wretched door--to where? Home? Heaven? Peace?--would never open, and at the same time he seemed resolved, ready to do his bit even though he couldn't possibly know what sacrifices that would require. Had he been kept here, too--in a place he didn't belong, serving in a war in which he hadn't enlisted, to rescue sparrows and soldiers and shopgirls and Shakespeare? To tip the balance?

* There are a hundred ways a man can bleed to death. And he can be pulled from the rubble of bitterness, of despair, as well as the wreckage of the Phoenix. And which rescue is the more real? Nothing you could have done for me... was more important than the restoration of my hope.

#### Their Eyes Were Watching God, by Zora Neale Hurston
* There are years that ask questions and years that answer.

* Love is lak de sea. It’s uh movin’ thing, but still and all, it takes its shape from de shore it meets, and it’s different with every shore.

* Some people could look at a mud puddle and see an ocean with ships.

* She had waited all her life for something, and it had killed her when it found her.

* No hour is ever eternity, but it has its right to weep.

#### The Bluest Eye, by Toni Morrison
* Love is never any better than the lover. Wicked people love wickedly, violent people love violently, weak people love weakly, stupid people love stupidly, but the love of a free man is never safe. There is no gift for the beloved. The lover alone possesses his gift of love. The loved one is shorn, neutralized, frozen in the glare of the lover’s inward eye.

* Anger is better. There is a sense of being in anger. A reality and presence. An awareness of worth. It is a lovely surging.

* Beauty was not simply something to behold; it was something one could do.

* We mistook violence for passion, indolence for leisure, and thought recklessness was freedom.

* She left me the way people leave a hotel room. A hotel room is a place to be when you are doing something else. Of itself it is of no consequence to one's major scheme. A hotel room is convenient. But its convenience is limited to the time you need it while you are in that particular town on that particular business; you hope it is comfortable, but prefer, rather, that it be anoymous. It is not, after all, where you live.

#### The Strangers, by Katherena Vermette
* Summer was always the worst season. Everyone always complained about winter, but winter was simple, you just didn't go outside. Summer always tried to sneak in where it was not wanted.

* And I knew. Again. Just like so many of the things I want, or used to hope for, it was never going to happen.

#### Cibola Burn (The Expanse #4), by James SA Corey
* “Right,” Holden said. “No coffee. This is a terrible, terrible planet.” 
* Once is never. Twice is always.

* Later, when you're wishing we had this stuff, I am going to be merciless in my mockery. And then we'll die.

* A person can fail the people they love just by being who they are.

* “Stop making me fall in love with you, Cap, we both know it can’t go anywhere.”

* If you start feeling wonderful and powerful and like you’ve seen the face of God, you’re having a euphoric attack.

* That was the danger of being old and a politician. Habits outlived the situations that created them. Policies remained in place after the situations that inspired them had changed.

* Sure, humans had invaded an extra-dimensional space with wormholes to points scattered across the galaxy, but they'd remembered to bring ferns.

#### Sula, by Toni Morrison
* In a way, her strangeness, her naiveté, her craving for the other half of her equation was the consequence of an idle imagination. Had she paints, or clay, or knew the discipline of the dance, or strings, had she anything to engage her tremendous curiosity and her gift for metaphor, she might have exchanged the restlessness and preoccupation with whim for an activity that provided her with all she yearned for. And like an artist with no art form, she became dangerous.

* It is sheer good fortune to miss somebody long before they leave you.

* It was a fine cry - loud and long - but it had no bottom and it had no top, just circles and circles of sorrow.

* There in the center of that silence was not eternity but the death of time and a loneliness so profound the word itself had no meaning. 

* Every now and then she looked around for tangible evidence of his having ever been there. Where were the butterflies? the blueberries? the whistling reed? She could find nothing, for he had left nothing but his stunning absence.

#### Nemesis Games (The Expanse #5), by James SA Corey
* You can tell you’ve found a really interesting question when nobody wants you to answer it.

* Looking back through history, there are a lot more men who thought they were Alexander the Great than men who actually were.

* “Here’s the thing,” Amos said. “If you did go in there, you might feel like you had to do something. And then I might feel like I had to do something. And then we’d all be doing things, and we’d all wind up having a worse day, just in general.” 

* “Alien superweapons were used,” Alex said, walking into the room, sleep-sweaty hair standing out from his skull in every direction. “The laws of physics were altered, mistakes were made.” 

* Things changed, and they didn’t change back. But sometimes they got better.

* The pleasantries were just ritual, but ritual was important. In Amos’ experience the more dangerous any two people were, the more carefully polite their social interactions tended to be. The loud, blustering ones were trying to get the other guy to back down. They wanted to stay out of a fight. The quiet ones were figuring out how to win it.

* Realizing you’ve got shit on your fingers is the first step toward washing your hands.

* Probably the most common last words that day were going to be Huh, that’s weird. That or Oh shit.

#### Doomsday Book (Oxford Time Travel #1), by Connie Willis
* I wanted to come, and if I hadn’t, they would have been all alone, and nobody would have ever known how frightened and brave and irreplaceable they were.

* None of the things one frets about ever happen. Something one's never thought of does.

#### Crossroads, by Jonathan Franzen
* He wondered if an action, to qualify as authentically good, needed not only to be untainted by self-interest but also to bring no pleasure of any kind.

* The dream of a novel was more resilient than other kinds of dreaming. It could be interrupted in mid-sentence and snapped back into later.

* He was realizing too late that old people weren't entirely stupid.

* It’s like there are these words, they’re out there in the world, and you start wondering what it would be like to say them. Words have their own power—they create the feeling, just by the fact of your saying them.

* Your father doesn’t look to our Savior but to what other men think of him. He preaches love but holds a grudge like no mans business.

#### The Light Fantastic (Discworld #2), by Terry Pratchett
* “Inside every sane person there's a madman struggling to get out," said the shopkeeper. "That's what I've always thought. No one goes mad quicker than a totally sane person.” 

* The sun rose slowly, as if it wasn't sure it was worth all the effort.

* Grinning like a necrophiliac in a morgue.

* The important thing about having lots of things to remember is that you’ve got to go somewhere afterwards where you can remember them, you see? You’ve got to stop. You haven’t really been anywhere until you’ve got back home.

* It looked like the sort of book described in library catalogues as 'slightly foxed', although it would be more honest to admit that it looked as though it had been badgered, wolved and possibly beared as well.

* He moved in a way that suggested he was attempting the world speed record for the nonchalant walk.

* The disc, being flat, has no real horizon. Any adventurous sailor who got funny ideas from staring at eggs and oranges for too long and set out for the antipodes soon learned that the reason why distant ships sometimes looked as though they were disappearing over the edge of the world was that they were disappearing over the edge of the world.

#### Us Against You (Beartown #2), by Fredrik Backman
* What does it take to be a good parent? Not much. Just everything. Absolutely everything.

* Everyone is a hundred different things, but in other people’s eyes we usually get the chance to be only one of them.

* The complicated thing about good and bad people alike is that most of us can be both at the same time.

* He’s twelve years old, and this summer he learns that people will always choose a simple lie over a complicated truth, because the lie has one unbeatable advantage: the truth always has to stick to what actually happened, whereas the lie just has to be easy to believe.

* It’s hard to care about people. Exhausting, in fact, because empathy is a complicated thing. It requires us to accept that everyone else’s lives are also going on the whole time. We have no pause button for when everything gets too much for us to deal with, but then neither does anyone else.

* Death does that to us, it’s like a phone call, you always remember exactly what you should have said the moment you hang up.

* They run only where there are lights. They don’t say anything but are both thinking the same thing: guys never think about light, it just isn’t a problem in their lives. When guys are scared of the dark, they’re scared of ghosts and monsters, but when girls are scared of the dark, they’re scared of guys.

* The truth about most people is as simple as it is unbearable: we rarely want what is best for everyone; we mostly want what’s best for ourselves.

* The best friends of our childhoods are the loves of our lives, and they break our hearts in worse ways.

#### The Fated Sky (Lady Astronaut Universe #2), by Mary Robinette Kowal
* My mother once told me that an apology wasn’t about being right or wrong, but showing that the relationship was more important than the problem.

* A donut is such a humble food until you really contemplate it. The glaze had begun to crystallize as the donut drew the moisture out of the sugar, leaving a sweet shell that separated as I bit into it, to reveal a delicate interior. Sugar and yeast and butter and God … God was in the donut.

* I am trying to remember that you mean well. But at the moment, I cannot take the protestations of a well-meaning white woman. I do not have the energy to reassure you or to pretend I am happy and content with my lot in life.

#### All Systems Red (Murderbot Diaries #1), by Martha Wells
* I could have become a mass murderer after I hacked my governor module, but then I realized I could access the combined feed of entertainment channels carried on the company satellites. It had been well over 35,000 hours or so since then, with still not much murdering, but probably, I don't know, a little under 35,000 hours of movies, serials, books, plays, and music consumed. As a heartless killing machine, I was a terrible failure.

* I liked the imaginary people on the entertainment feed way more than I liked real ones, but you can’t have one without the other.

* They were all so nice and it was just excruciating. I was never taking off the helmet again. I can't do even the half-assed version of this stupid job if I have to talk to humans.

* “I remember every word ever said to me." That was a lie. Who would want that? Most of it I delete from permanent memory.

* The sense of urgency just wasn’t there. Also, you may have noticed, I don’t care.

* It’s wrong to think of a construct as half bot, half human. It makes it sound like the halves are discrete, like the bot half should want to obey orders and do its job and the human half should want to protect itself and get the hell out of here. As opposed to the reality, which was that I was one whole confused entity, with no idea what I wanted to do. What I should do. What I needed to do.

#### The Relentless Moon (Lady Astronaut Universe #3), by Mary Robinette Kowal
* There’s a thing that happens to people when they are helpless. They become afraid of things that in their normal life wouldn’t faze them at all.

* This is the value of ritual and repetition, be it in a cockpit or in a church pew. Familiarity gives us room to breath and to think.

* I respect secrets, but I would rather have you tell me that something is off-limits than have you give me misinformation. A hole in the data, I can work with.

* I needed help, because the problem with packing all your emotions away so you don’t become a weeping mass on the floor is that it leaves you cold and dead and ready to drive a trowel into someone’s guts and watch them choke on their own blood and that would cause problems.

* I will honestly never understand why men, who seem to spend so much of their lives thinking about sex, get so flustered when a woman discusses it.

#### To Say Nothing of the Dog (Oxford Time Travel #2), by Connie Willis
* Cats, as you know, are quite impervious to threats.

* The reason Victorian society was so restricted and repressed was that it was impossible to move without knocking something over.

* People will buy anything at jumble sales,' I said. 'At the Evacuated Children Charity Fair a woman bought a tree branch that had fallen on the table.

* Come here, cat. You wouldn’t want to destroy the space-time continuum, would you? Meow. Meow.

* History was indeed controlled by blind forces, as well as character and courage and treachery and love. And accident and random chance. And stray bullets and telegrams and tips. And cats.

* I was never going to get any sleep. I was going to have Alice in Wonderland conversation after Alice in Wonderland conversation until I died of exhaustion. Here, in the restful, idyllic Victorian era.

* There is nothing more helpful than shouted instructions, particularly incomprehensible ones.

* One of the first symptoms of time-lag is a tendency to maudlin sentimentality, like an Irishman in his cups or a Victorian poet cold-sober.

#### Artificial Condtion (Murderbot Diaries #2), by Martha Wells
* I didn’t care what humans were doing to each other as long as I didn’t have to a) stop it or b) clean up after it.

* Young humans can be impulsive. The trick is keeping them around long enough to become old humans.

* So they made us smarter. The anxiety and depression were side effects.

* I felt this would be the point where a human would sigh, so I sighed.

* Humans should really do more research. There were operating manuals that would have warned her not to fuck with us.

* Not that a lot of them had asked for it, or had listened to me. Not that I’m bitter about that, or anything.

#### The Universal Baseball Association Inc., Henry J. Waugh, Prop., by Robert Coover
* And so, finally, he’d found his way back to baseball. Nothing like it really. Not the actual game so much—to tell the truth, real baseball bored him—but rather the records, the statistics, the peculiar balances between individual and team, offense and defense, strategy and luck, accident and pattern, power and intelligence. And no other activity in the world had so precise and comprehensive a history, so specific an ethic, and at the same time, strange as it seemed, so much ultimate mystery.

* American baseball, by luck, trial, and error, and since the famous playing rules council of 1889, had struck on an almost perfect balance between offense and defense, and it was that balance, in fact, that and the accountability—the beauty of the records system which found a place to keep forever each least action—that had led Henry to baseball as his final great project.

#### Ancillary Sword (Imperial Radch #2), by Ann Leckie
* When they behave properly, you will say there is no problem. When they complain loudly, you will say they cause their own problems with their impropriety. And when they are driven to extremes, you say you will not reward such actions. What will it take for you to listen?

* For my part,” I replied, “I find forgiveness overrated. There are times and places when it’s appropriate. But not when the demand that you forgive is used to keep you in your place.

* Translator Dlique was saying, very earnestly, “Eggs are so inadequate, don’t you think? I mean, they ought to be able to become anything, but instead you always get a chicken. Or a duck. Or whatever they’re programmed to be. You never get anything interesting, like regret, or the middle of the night last week."

* And it’s so easy to just go along. So easy not to see what’s happening. And the longer you don’t see it, the harder it becomes to see it, because then you have to admit that you ignored it all that time.

* Water will wear away stone, but it won’t cook supper. Everything has its own strengths. Said with enough irony, it could also imply that since the gods surely had a purpose for everyone the person in question must be good for something, but the speaker couldn’t fathom what it might be.

* Memory is an event horizon. What’s caught in it is gone but it’s always there.

#### Ancillary Mercy (Imperial Radch #3), by Ann Leckie
* There is always more after the ending. Always the next morning, and the next. Always changes, losses and gains. Always one step after the other. Until the one true ending that none of us can escape. But even that ending is only a small one, larges as it looms for us. There is still the next morning for everyone else. For the vast majority of the rest of the universe that ending might as well not ever have happened. Every ending is an arbitrary one. Everything ending is from another angle, not really an ending.

* There are two parts to reacting aren't there? How you feel and what you do. And its the thing you do that is the important one.

* You don’t need to know the odds. You need to know how to do the thing you’re trying to do. And then you need to do it.

* We sit here arguing, we can hardly agree on anything, and then you go straight to my heart like that. We must be family.

* She was born surrounded by wealth and privilege. She thinks she’s learned to question that. But she hasn’t learned quite as much as she thinks she has, and having that pointed out to her, well, she doesn’t react well to it.

* Every ending is an arbitrary one. Every ending is, from another angle, not really an ending.

#### Rogue Protocol (Murderbot Diaries #3), by Martha Wells
* There needs to be an error code that means “I received your request but decided to ignore you.

* I hate caring about stuff. But apparently once you start, you can't just stop.

* They were all annoying and deeply inadequate humans, but I didn’t want to kill them. Okay, maybe a little.

* If you had to take care of humans, it was better to take care of small soft ones who were nice to you and thought you were great because you kept preventing them from being murdered.

* Why yes, I did want to disengage the safety protocols, thanks for asking.

#### Babylon's Ashes (The Expanse #6), by James SA Corey
* I thought if you told people *facts*, they'd draw their conclusions, and because the facts were true, the conclusions mostly would be too. But we don't run on facts. We run on stories about things. About people.

* Against all evidence, I keep thinking the assholes are outliers.

* Whoever screws up last loses. Whoever screws up second to last wins. That’s what war is.

* All beautiful things should have just a little sorrow about them. Made them seem real.

* I mean, weird, dead alien technology with effects we don’t understand sweeping whole ships away without leaving a trace or explanation. That’s probably safe to play with, right?

#### Exit Strategy (Murderbot Diaries #4), by Martha Wells
* I was having an emotion, and I hate that.

* Possibly I was overthinking this. I do that; it’s the anxiety that comes with being a part-organic murderbot. The upside was paranoid attention to detail. The downside was also paranoid attention to detail.

* It would have been hilarious if I wasn’t about to die. It was still a little hilarious.

* So the plan wasn't a clusterfuck, it was just circling the clusterfuck target zone, getting ready to come in for a landing.

* Disinformation, which is the same as lying but for some reason has a different name, is the top tactic in corporate negotiation/warfare.

#### The Overstory, by Richard Powers
* The best arguments in the world won't change a person's mind. The only thing that can do that is a good story.

* What you make from a tree should be at least as miraculous as what you cut down.

* This is not our world with trees in it. It's a world of trees, where humans have just arrived.

* People aren’t the apex species they think they are. Other creatures-bigger, smaller, slower, faster, older, younger, more powerful-call the shots, make the air, and eat sunlight. Without them, nothing.

* But people have no idea what time is. They think it’s a line, spinning out from three seconds behind them, then vanishing just as fast into the three seconds of fog just ahead. They can’t see that time is one spreading ring wrapped around another, outward and outward until the thinnest skin of Now depends for its being on the enormous mass of everything that has already died.

* Life will cook; the seas will rise. The planet’s lungs will be ripped out. And the law will let this happen, because harm was never imminent enough. Imminent, at the speed of people, is too late. The law must judge imminent at the speed of trees.

* A seed that lands upside down in the ground will wheel --root and stem--in a great U-turn until it rights itself. But a human child can know it's pointed wrong and still consider the direction well worth a try.

* We found that trees could communicate, over the air and through their roots. Common sense hooted us down. We found that trees take care of each other. Collective science dismissed the idea. Outsiders discovered how seeds remember the seasons of their childhood and set buds accordingly. Outsiders discovered that trees sense the presence of other nearby life. That a tree learns to save water. That trees feed their young and synchronize their masts and bank resources and warn kin and send out signals to wasps to come and save them from attacks. “Here’s a little outsider information, and you can wait for it to be confirmed. A forest knows things. They wire themselves up underground. There are brains down there, ones our own brains aren’t shaped to see. Root plasticity, solving problems and making decisions. Fungal synapses. What else do you want to call it? Link enough trees together, and a forest grows aware.

* There is no knowing for a fact. The only dependable things are humility and looking.

#### Persepolis Rising (The Expanse #7), by James SA Corey
* In his opinion, faith was generally for people who were bad at math.

* I actually read history. It’s like reading prophecy, you know.

* Your empire’s hands look a lot cleaner when you get to dictate where history begins and what parts of it don’t count.

* Don’t let things sit for too long. It’s always tempting to just ignore the things that aren’t actually on fire just at the moment, but then you’re also committing to spend your time putting out fires.

* Tribalism was an irrational position, and it was impossible to defeat an irrational position with a rational argument.

* Time was supposed to heal all wounds. To Drummer, that was just a nice way of saying that if she waited long enough, none of the things that seemed important to her would turn out to matter.

* That seemed to be the human pattern—reach out to the unknown and then make it into the sort of thing you left in the first place.

* Because we’re human, and humans are mean, independent monkeys that reached their greatness by killing every other species of hominid that looked at us funny.

#### A Memory Called Empire (Teixcalaan #1), by Arkady Martine
* So much of who we are is what we remember and retell.

* The problem with sending messages was that people responded to them, which meant one had to write more messages in reply.

* Our memory is a more perfect world than the universe; it gives life back to those who no longer exist.

* Histories are always worse by the time they get written down.

* Poetry is for the desperate, and for people who have grown old enough to have something to say.

#### Tiamat's Wrath (The Expanse #8), by James SA Corey
* Distributed responsibility is the problem. One person gives the order, another carries it out. One can say they didn’t pull the trigger, the other that they were just doing what they were told, and everyone lets themselves off the hook.

* There are people I love. There are people who have loved me. I fought for what I believed, protected those I could, and stood my ground against the encroaching darkness. Good enough.

* But pacifism only works when your enemy has a conscience.

* There was no better way to seem trustworthy than to be liked by a dog, and there was no better way to convince a dog to like you than bribery.

* The people who have power over you are weak too. They shit and bleed and worry that their children don’t love them anymore. They’re embarrassed by the stupid things they did when they were young that everyone else has forgotten. And so they’re vulnerable. We all define ourselves by the people around us, because that’s the kind of monkey we are. We can’t transcend it. So when they watch you, they hand you the power to change what they are too.

* I’m not sure dying free is as attractive when it stops being rhetorical.

* Growing older was a falling away of everything that didn’t matter. And a deepening appreciation of all the parts that were important enough to stay.

* That’s the thing about autocracy. It looks pretty decent while it still looks pretty decent. Survivable, anyway. And it keeps looking like that right up until it doesn’t. That’s how you find out it’s too late.

* There are only a couple kinds of anger. You get angry because you're afraid of something or you get angry because you're frustrated.

#### A Desolation Called Peace (Teixcalaan #2), by Arkady Martine
* Wait for the real problem, Your Excellency. Don’t borrow trouble that doesn’t come to you on its own.

* She’s a barbarian, but don’t hold it against her. She’s brilliant.

* It is the minds of a people that have to stay free. Bodies die, or suffer, or are imprisoned. Memory lasts.

#### Britt-Marie Was Here, by Fredrik Backman
* One morning you wake up with more life behind you than in front of you, not being able to understand how it’s happened.

* A human being, any human being at all, has so perishingly few chances to stay right there, to let go of time and fall into the moment. And to love someone without measure, explode with passion... A few times when we are children, maybe, for those of us who are allowed to be... But after that? How many breaths are we allowed to take beyond the confines of ourselves? How many pure emotions make us cheer out loud without a sense of shame? How many chances do we get to be blessed by amnesia? All passion is childish, it's banal and naive, it's nothing we learn, it's instinctive, and so it overwhelms us... Overturns us... It bears us away in a flood... All other emotions belong to the earth, but passion inhabits the universe. That is the reason why passion is worth something. Not for what it gives us, but for what it demands that we risk - our dignity, the puzzlement of others in their condescending shaking heads...

* A human being may not choose her circumstances, but she does choose her actions.

* A few years turned into more years, and more years turned into all years. Years have a habit of behaving like that.

* You have to understand that when one is just standing there looking, then just for a second one is ready to jump. If one does it, one dares to do it. But if one waits, it’ll never happen.

* You love football because it is instinctive. If a ball comes rolling down the street you give it a punt. You love it for the same reason you fall in love. Because you don't know how to avoid it.

* If you support Tottenham you always give more love than you get back... Tottenham is the worst kind of bad team, because they're almost good. They always promise that they're going to be fantastic. They make you hope. So you go on loving them and they carry on finding more and more innovative ways of disappointing you. 

#### A Master of Djinn, by P. Djeli Clark
* "Why is everyone so slavish to texts written thousands of years ago?” he snapped. “Gods can change. Grow apart. Try new things. Besides, Set was a jerk."

* I don’t have sad tales to tell you. I’m not some tragic character from a story, lost between two worlds. I revel in who I am. What I am.

* Rich people always have enemies. Usually, that’s how they became rich.

* “Usually the secrets we keep deep down, ain’t meant to hurt other people,” he said. “Not saying they won’t, but not through intentions. Those deep secrets, we hide away because we’re afraid what other people might think. How they might judge us, if they knew. And nobody’s judgment we scared of more than the one we give our hearts to. Besides, everybody got secrets. Even you, I’m betting.” 

* And among His wonders is the creation of the heavens and the earth, and the diversity of your tongues and colors. For in this, behold, there are messages indeed for all who are possessed of innate knowledge.

#### Detransition, Baby, by Torrey Peters
* She knew that no matter how you self-identify ultimately, chances are that you succumb to becoming what the world treats you as.

* All my white girlfriends just automatically assume that reproductive rights are about the right to not have children, as if the right and naturalness of motherhood is presumptive. But for lots of other women in this country, the opposite is true. Think about black women, poor women, immigrant women. Think about forced sterilization, about the term ‘welfare queens,’ or ‘anchor babies.’ All of that happened to enforce the idea that not all motherhoods are legitimate.

#### Leviathan Falls (The Expanse #9), by James SA Corey
* The stars are still there,” she said. “We’ll find our own way back to them.

* “When people don’t know anything,” Amos said, “they love having meetings to talk about it.” 

* “I absolutely believe that people are more good on balance than bad,” he said. “All the wars and all of the cruelty and all of the violence. I’m not looking away from any of that, and I still think there’s something beautiful about being what we are. History is soaked in blood. The future probably will be too. But for every atrocity, there’s a thousand small kindnesses that no one noticed. A hundred people who spent their lives loving and caring for each other. A few moments of real grace.” 

* I think about all the things we could have done, all the miracles we could have achieved, if we were all just a little bit better than it turns out we are.

* You’re overthinking this, Cap’n. You got now and you got the second your lights go out. Meantime is the only time there is. All that matters is what we do during it.

* We also both know that when it comes to getting people to deny their own immediate needs in favor of a greater good, asking nicely almost never works.

* There was so much that they’d never seen or understood. They’d all just bumbled through, using the gates as shortcuts and hoping for the best. A species of beautiful idiots.

#### Jonny Appleseed, by Joshua Whitehead
* ...leaving home always hurts--home isn't a space, it's a feeling. You have to feel home and to feel it, you have to sense it: smell it, taste it, hear it. And it isn't always comfortable--

* And I thought about now, thought about my mom’s advice: if I want to survive, I’d have to leave. But it’s hard, you know? Each second I’m away from home is time that’s gone forever, driving us that much closer to the end. How much more time do we really have? And by whose measure? Like she said, maybe there aren’t that many more moments to come. But at least there was this one.

#### Memory's Legion (The Expanse Shorts), by James SA Corey
* We’re at the start of something here. We can’t let it slide. If it’s okay now, it’s okay forever. You plug a leak when it’s small, or you suffer when it’s big.

* Doing the right thing has to be enough in itself. It’s not about getting the pat on the head.

* The only right you have with anyone in this life is the right to walk away.

* ...and he wore a thin mustache like it was a joke he was in on.

* He stared out at all of them like an actor who’d just forgotten the St. Crispin’s Day speech. “Get ready.”

#### Network Effect (Murderbot Diaries #5), by Martha Wells
* “Just remember you’re not alone here.” I never know what to say to that. I am actually alone in my head, and that’s where 90 plus percent of my problems are.

* Normal = neutral expression concealing existential despair and brain-crushing boredom.

* There is a lot about what is going on here that I don’t understand. But I am participating anyway.

* I wasn’t sure exactly what “okay” would involve, but I was willing to settle for “unmurdered.

* You know that thing humans do where they think they’re being completely logical and they absolutely are not being logical at all, and on some level they know that, but can’t stop? Apparently it can happen to SecUnits, too.

* Ugh, emotions.

* “Can I ask you a question?” I never know how to answer this. Should I go with my first impulse, which is always “no” or just give in to the inevitable?

#### Fugitive Telemetry (Murderbot Diaries #6), by Martha Wells
* Yeah, good luck with that. Trying to get humans not to touch dangerous things was a full-time job.

* It had been such a stupid question, I had forgotten not to have an expression.

* Humans touch stuff all the time, I wish they wouldn’t.

* Humans do the “make it a question so it doesn’t sound so bad” thing and it still sounds bad.

* Don’t look at me like that’s my fault. I’m just telling you shit I know.

#### Once There Were Wolves, by Charlotte McConaghy
* There are languages without words and violence is one of them.

* My father used to say the world turned wrong when we started separating ourselves from the wild, when we stopped being one with the rest of nature, and sat apart.

* This is the thing, isn’t it? This is the fear they live with now. The children in us long for monsters to take forms we understand. They want to fear the wolves because they don’t want to fear each other.

* It’s not a forest. It’s one tree. One huge organism. It’s called the trembling giant and it’s the oldest living thing on this planet, and the largest. Some think it could be a million years old. And it’s dying. We’re killing it.

#### The Snow Child, by Eowyn Ivey
* In my old age, I see that life itself is often more fantastic and terrible than the stories we believed as children, and that perhaps there is no harm in finding magic among the trees.

* We never know what is going to happen, do we? Life is always throwing us this way and that. That’s where the adventure is. Not knowing where you’ll end up or how you’ll fare. It’s all a mystery, and when we say any different, we’re just lying to ourselves. Tell me, when have you felt most alive?

* To believe, perhaps you had to cease looking for explanations and instead hold the little thing in your hands as long as your were able before it slipped like water between your fingers.

* Sometimes these things happen. Life doesn't go the way we plan or hope, but we don't have to be so angry, do we?

* I guess maybe I don't want to be warm and safe. I want to live.

#### Shuggie Bain, by Douglas Stuart
* Sadness made for a better houseguest; at least it was quiet, reliable, consistent.

* Flames are not just the end, they are also the beginning. For everything that you have destroyed can be rebuilt. From your own ashes you can grow again.

* The morning light was the colour of too-milky tea. It snuck into the bedsit like a sly ghost, crossing the carpet and inching slowly up his bare legs.

* She’d looked as happy as he could ever remember, and he was surprised how this hurt. It was all for the red-headed man. He had done what Shuggie had been unable to do.

* She was no use at maths homework, and some days you could starve rather than get a hot meal from her, but Shuggie looked at her now and understood this was where she excelled. Everyday with the make-up on and her hair done, she climbed out of her grave and held her head high. When she had disgraced herself with drink, she got up the next day, put on her best coat, and faced the world. When her belly was empty and her weans were hungry, she did her hair and let the world think otherwise.

#### A Prayer for the Crown-Shy (Monk & Robot #2), by Becky Chambers
* You don’t have to have a reason to be tired. You don’t have to earn rest or comfort. You’re allowed to just be.

* How am I supposed to tell people they’re good enough as they are when I don’t think I am?

* The thing about fucking off to the woods is that unless you are a very particular, very rare sort of person, it does not take long to understand why people left said woods in the first place.

* And to that end, welcome comfort, for without it, you cannot stay strong.

* You know how it is; sometimes you just want to have a moment between yourself and a turtle and no one else.

* Well, that's the nice thing about trees," Mosscap put its hands on its hips as it looked around. "They're not going anywhere. You can take all the time you need to get to know them.

#### The Ocean at the End of the Lane, by Neil Gaiman
* Grown-ups don't look like grown-ups on the inside either. Outside, they're big and thoughtless and they always know what they're doing. Inside, they look just like they always have. Like they did when they were your age. Truth is, there aren't any grown-ups. Not one, in the whole wide world.

* I do not miss childhood, but I miss the way I took pleasure in small things, even as greater things crumbled. I could not control the world I was in, could not walk away from things or people or moments that hurt, but I took joy in the things that made me happy.

* Nobody looks like what they really are on the inside. You don’t. I don’t. People are much more complicated than that. It’s true of everybody.

* Adults follow paths. Children explore. Adults are content to walk the same way, hundreds of times, or thousands; perhaps it never occurs to adults to step off the paths, to creep beneath rhododendrons, to find the spaces between fences. I was a child, which meant that I knew a dozen different ways of getting out of our property and into the lane, ways that would not involve walking down our drive.

* Monsters come in all shapes and sizes. Some of them are things people are scared of. Some of them are things that look like things people used to be scared of a long time ago. Sometimes monsters are things people should be scared of, but they aren't.

#### The Love Songs of W.E.B. Du Bois, by Honoree Fanonne Jeffers
* We are the earth, the land. The tongue that speaks and trips on the names of the dead as it dares to tell these stories of a woman’s line. Her people and her dirt, her trees,

* The year before, I’d been so anxious to do research in the Old South Collections. The archives had fascinated me. Made me happy for the first time in my socially awkward life. But there was a catch when you did research on slavery: you couldn’t only focus on the parts you wanted. You had to wade through everything, in order to get to the documents you needed. You had to look at the slave auctions and whippings. The casual cruelty that indicated the white men who’d owned Black folks didn’t consider them human beings. When I began doing research in the Pinchard family papers, I wasn’t reading about strangers anymore. These were my own ancestors, Black and white. 

* Born in the City, her husband wasn’t familiar with the taste of healthy, green food you had picked only hours before. The sight of earth not taken over by concrete. That in darkness, if there was no trouble, the only sounds came from small beings. He didn’t know that you could ache for a place, even when it had hurt you so badly.

* But first you got to get out of the library sometimes and meet somebody, 'cause it ain't legal to marry books.

* Even in a place of sorrow, time passes. Even in a place of joy. Do not assume that either keeps life from continuing.

* These are the incongruities of memory. It is hard to hold on to the entirety of something, but pieces may be held up to light.

#### Sea of Tranquility, by Emily St. John Mandel
* My point is, there’s always something. I think, as a species, we have a desire to believe that we’re living at the climax of the story. It’s a kind of narcissism. We want to believe that we’re uniquely important, that we’re living at the end of history, that now, after all these millennia of false alarms, now is finally the worst that it’s ever been, that finally we have reached the end of the world.

* Pandemics don’t approach like wars, with the distant thud of artillery growing louder every day and flashes of bombs on the horizon. The arrive in retrospect, essentially. It’s disorienting. The pandemic is far away and then it’s all around you with seemingly no intermediate step.

* It’s shocking to wake up in one world and find yourself in another by nightfall, but the situation isn’t actually all that unusual. You wake up married, then your spouse dies over the course of the day. You wake up in peacetime and by noon your country is at war; you wake up in ignorance and by the evening it’s clear that a pandemic is already here.

* There’s a low-level, specific pain in having to accept that putting up with you requires a certain generosity of spirit in your loved ones.

* If definitive proof emerges that we’re living in a simulation, the correct response to that news will be So what. A life lived in a simulation is still a life.

* “It seems like it’s been fairly well contained,” but here’s an epidemiological question: if you’re talking about outbreaks of infectious disease, isn’t fairly well contained essentially the same thing as not contained at all?

#### Redshirts, by John Scalzi
* I don't care whether I really exist or don't, whether I'm real or fictional. What I want right now is to be the person who decides my own fate.

* Sooner or later the Narrative will come for each of us.

* "But define 'completely ridiculous shit,'" Duvall said. "Does space travel count? Contact with alien races? Does quantum physics count? Because I don't understand that crap at all. As far as I'm concerned, quantum physics could have been written by a hack.

* For all we know, this”—he scrolled up on the phone screen to find a label—“this Wikipedia information database here is compiled by complete idiots.

* Ensign Davis thought, Screw this, I want to live, and swerved to avoid the land worms. But then he tripped and one of the land worms ate his face and he died anyway.

#### The Vanishing Half, by Britt Bennett
* Her death hit in waves. Not a flood, but water lapping steadily at her ankles. You could drown in two inches of water. Maybe grief was the same.

* People thought that being one of a kind made you special. No, it just made you lonely. What was special was belonging with someone else.

* A town always looked different once you'd returned, like a house where all the furniture had shifted three inches. You wouldn't mistake it for a stranger's house but you'd keeping banging your shins on the table corners.

* The only difference between lying and acting was whether your audience was in on it, but it was all a performance just the same.

#### An Unkindness of Ghosts, by Rivers Solomon
* I am a boy and a girl and a witch all wrapped into one very strange, flimsy, indecisive body. Do you think my body couldn't decide what it wanted to be?

* Pretty was a strange thing to concern oneself over. Pretty was subjective and fallacious.

* People do not know what to make of me, and this pleases me. I don't want to be scrutable.

* The point is what you do when you don’t have the details. Do you interrogate? Do you examine? Or do you settle for the obvious answer?

* Poor, poor books. Lonely pages bound in lonely leather, their only company the occasional louse. They exist only to be read, and yet with no one there to read them, they might as well not have been bornt at all. I run my fingers along the spines of the books I can reach. I do it to affirm them. To let them know I'm a lover of stories even stories about alchematics or biology and other true things.

* You are mean because inside you’re tiny. So tiny you cannot hold up the weight of your own body. You must inflate your ego just to fill the skin. You float around like a helium balloon. Blown up and bloated and gassy and empty.

#### Harlem Shuffle, by Colson Whitehead
* Everyone had secret corners and alleys that no one else saw—what mattered were your major streets and boulevards, the stuff that showed up on other people’s maps of you.

* The way he saw it, living taught you that you didn't have to live the way you'd been taught to live. You came from one place but more important was where you decided to go.

* You have to have an inside you, she used to say, and an outside you. Ain't nobody's business who you are really, so it's up to you what you gave them.

#### Firekeeper's Daughter, by Angeline Boulley
* We love imperfect people. We can love them and not condone their actions and beliefs.

* Inaction is a powerful choice.

* When someone dies, everything about them becomes past tense. Except for the grief. Grief stays in the present. It’s even worse when you’re angry at the person. Not just for dying. But for how.

* Kindness is something that seems small, Daunis, but it's like tossing a pebble into a pond and the ripples reach further than you thought.

* Wisdom is not bestowed. In its raw state, it is the heartbreak of knowing things you wish you didn't.

* Some boats are made for the river and some for the ocean. And there are some who can go anywhere because they always know the way home.

#### Raven Stratagem (The Machineries of Empire #2), by Yoon Ha Lee
* I’m not a linguist, but do you ever think there’s something wrong with the things we do and don’t have words for?

* Immortality didn’t turn you into a monster. It merely showed you what kind of monster you already were.

* Even monsters seek companionship. Or an audience, anyway.

* Never ascribe to irrational benevolence what selfishness will explain.

* Of course, at some point you had to ask yourself how much legitimacy any government had that feared dissension within more than invasion from without, but if you had any desire for a quiet life, you kept those thoughts inside your skull.

#### This Is How You Lose the Time War, by Amal El-Mohtar & Max Gladstone
* Books are letters in bottles, cast into the waves of time, from one person trying to save the world to another.

* There’s a kind of time travel in letters, isn’t there? I imagine you laughing at my small joke; I imagine you groaning; I imagine you throwing my words away. Do I have you still? Do I address empty air and the flies that will eat this carcass? You could leave me for five years, you could return never—and I have to write the rest of this not knowing.

* I have built a you within me, or you have. I wonder what of me there is in you.

* Sometimes when you write, you say things I stopped myself from saying.

#### The Invisible Life of Addie Larue, by VE Schwab
* Books, she has found, are a way to live a thousand lives--or to find strength in a very long one.

* What is a person, if not the marks they leave behind?

* Three words, large enough to tip the world. I remember you.

* The old gods may be great, but they are neither kind nor merciful. They are fickle, unsteady as moonlight on water, or shadows in a storm. If you insist on calling them, take heed: be careful what you ask for, be willing to pay the price. And no matter how desperate or dire, never pray to the gods that answer after dark.

#### The Winners (Beartown #3), by Fredrik Backman
* He has seen good people capable of great evil, but also evil people capable of incredible light. It's the same everywhere. Almost everybody loves too much, hates too easily, forgives too little. But most people want the same things: to live in peace, to make their hearts beat a little slower when the night comes, to earn some money to support the ones they love.

* We fool ourselves that we can protect the people we love, because if we accepted the truth we’d never let them out of our sight.

* He’s the sort of person who runs toward a fire. No hesitation, no questions, he just runs. People like that are rare, but you know who they are when you see them.

* Our children never warn us that they’re thinking of growing up, one day they’re just too big to want to hold our hand, it’s just as well we never know when the last time is going to be or we’d never let 

* When you're young you believe that love is infatuation, but infatuation is simple, any child can become infatuated, fall in love. But real love? Love is a job for an adult. Love demands a whole person, all the best of you, all the worst. It has nothing to do with romance, because the hard part of a marriage isn't that I have to live seeing all your faults, but that you have to live with me seeing them. That I know everything about you now. Most people aren't brave enough to live without secrets. Everyone dreams about being invisible sometimes, no one dreams of being transparent.

* Clichés may be clichés, but they often start out as truths.

#### Night of the Living Rez, by Morgan Talty
* I wonder if How'd we get here? is the wrong question. Maybe the right question is How do we get out of here? Maybe that's the only question that matters.

#### Ninefox Gambit (The Machineries of Empire #1), by Yoon Ha Lee
* The problem with authority is that if you leave it lying around, others will take it away from you.

* But then, war is about taking the future away from people.

* The point of war is to rig the deck, drug the opponent, and threaten to kneecap their family if they don't fold.

* I once had someone swerve her tank out of our column and straight into a house. With a very large basement. Because she was too sleep-deprived to think. It's funny now, but it wasn't funny then. – Oh, who am I kidding, it was HILARIOUS, even if it was kind of a disaster. I laughed so hard my aide almost shot me.

#### Vicious (Villains #1), by VE Schwab
* Plenty of humans were monstrous, and plenty of monsters knew how to play at being human.

* When no one understands, that's usually a good sign that you're wrong.

* He wanted to care, he wanted to care so badly, but there was this gap between what he felt and what he wanted to feel, a space where something important had been carved out.

#### Revenant Gun (The Machineries of Empire #3), by Yoon Ha Lee
* The first rule of any game was to assume you could win, even if you had to hunt through the universe’s cracks for a strategy, even if you had to turn the pieces inside-out, even if you had to tell so many lies to the opponent that they couldn’t figure out which way was up.

* The presence of atrocity doesn’t mean you have to put your life on hold. You’ll arguably be better at dealing with the horrible things you have to witness, or even to perpetrate, if you allow yourself time to do the small, simple things that make you happy. Instead of looking for ways to destroy yourself.

* But that didn’t mean those things weren’t worth doing. Someone had to carry on with the small acts that kept civilization moving. And this time it was her turn.

#### My Grandmother Sends Her Regards and Apologizes, by Fredrik Backman
* People in the real world always say, when something terrible happens, that the sadness and loss and aching pain of the heart will “lessen as time passes,” but it isn’t true. Sorrow and loss are constant, but if we all had to go through our whole lives carrying them the whole time, we wouldn’t be able to stand it. The sadness would paralyze us. So in the end we just pack it into bags and find somewhere to leave it.

* Death’s greatest power is not that it can make people die, but that it can make people want to stop living.

* Because not all monsters were monsters in the beginning. Some are monsters born of sorrow.

* Having a grandmother is like having an army. This is a grandchild’s ultimate privilege: knowing that someone is on your side, always, whatever the details.

* One day at a time. One dream at a time. And one could say it’s right and one could say it’s wrong. And probably both would be right. Because life is both complicated and simple. Which is why there are cookies.

* Everything is complicated if no one explains it to you.

* People who have never been hunted always seem to think there’s a reason for it. ‘They wouldn’t do it without a cause, would they? You must have done something to provoke them.’ As if that was how oppression works.

#### Vengeful (Villains #2), by VE Schwab
* Perhaps she was glass. But glass is only brittle until it breaks. Then it’s sharp.

* Some people were matches, a bit of light and no heat. And some were furnaces, all heat but little light. And then, once in a blue moon, there was a bonfire, something so hot and bright you couldn't stand too near without burning.

#### Small Things Like These, by Claire Keegan
* As they carried along and met more people Furlong did and did not know, he found himself asking was there any point in being alive without helping one another? Was it possible to carry on along through all the years, the decades, through an entire life, without once being brave enough to go against what was there and yet call yourself a Christian, and face yourself in the mirror?

* It seemed both proper and at the same time deeply unfair that so much of life was left to chance.

* The worst was yet to come, he knew. Already he could feel a world of trouble waiting for him behind the next door, but the worst that could have happened was also already behind him; the thing not done, which could have been – which he would have had to live with for the rest of his life.

* It was easy to understand why women feared men with their physical strength and lust and social powers, but women, with their canny intuitions, were so much deeper: they could predict what was to come long before it came, dream it overnight, and read your mind.

* But it cut him, all the same, to see one of his own so upset by the sight of what other children craved and he could not help but wonder if she'd be brave enough or able for what the world had in store.

### Non-Fiction
#### Entangled Life: How Fungi Make Our Worlds, Change Our Minds & Shape Our Futures, by Merlin Sheldrake
* The difference between animals and fungi is simple: Animals put food in their bodies, whereas fungi put their bodies in the food.

* A mycelial network is a map of a fungus’s recent history and is a helpful reminder that all life-forms are in fact processes not things. The “you” of five years ago was made from different stuff than the “you” of today. Nature is an event that never stops. As William Bateson, who coined the word genetics, observed, “We commonly think of animals and plants as matter, but they are really systems through which matter is continually passing.

* The authors of a seminal paper on the symbiotic view of life take a clear stance on this point. “There have never been individuals,” they declare. “We are all lichens.

* Fungi make worlds. They also unmake them. There are lots of ways to catch them in the act. When you cook mushroom soup, or just eat it. When you go out gathering mushrooms, or buy them. When you ferment alcohol, plant a plant, or just bury your hands in the soil; and whether you let a fungus into your mind, or marvel at the way that it might enter the mind of another. Whether you’re cured by a fungus, or watch it cure someone else; whether you build your home from fungi, or start growing mushrooms in your home, fungi will catch you in the act.
If you’re alive, they already have.

* Anthropomorphism is usually thought of as an illusion that arises like a blister in soft human minds: untrained, undisciplined, unhardened. There are good reasons for this: when we humanise the world, we may prevent ourselves from understanding the lives of other organisms on their own terms. But are there things this stance might lead us to pass over – or forget to notice?

* A slime-mold enthusiast told me about a test he had performed. He frequently got lost in IKEA stores and would spend many minutes trying to find the exit. He decided to challenge his slime molds with the same problem and built a maze based on the floor plan of his local IKEA. Sure enough, without any signs or staff to direct them, the slime molds soon found the shortest path to the exit. “You see,” he said with a laugh, “they’re cleverer than me.” 

#### The Disordered Cosmos: A Journey into Dark Matter, Spacetime, and Dreams Deferred, by Chanda Prescod-Weinstein
* Access to a dark night sky—to see and be inspired by the universe as it really is—should be a human right, not a luxury for the chosen few.

* Science is supposedly about asking questions, except about scientists and how science is done.

* I believe we can keep what feels wondrous about the search for a mathematical description of the universe while disconnecting this work from its historical place in the hands of violently colonial nation-states.

* Everywhere we go, no matter how hard we try to avoid it, capitalism follows us.

* Much more interesting is the question of how we get free. What does freedom look like? When I put this question to artist Shanequa Gay, she told me, "Freedom looks like choice-making without having to consider so many others when I make those choices." I hear in Shanequa's response a deep cry for space to self-actualize, to not always be stuck in survival mode.

* Part of science, therefore, involves writing a dominant group’s social politics into the building blocks of a universe that exists far beyond and with little reference to our small planet and the apes that are responsible for melting its polar ice caps.

#### Things My Son Needs to Know About the World, by Fredrik Backman
* I just want you to know that I love you. Once you’re older, you’ll realize that I made an endless line of mistakes during your childhood. I know that. I’ve resigned myself to it. But I just want you to know that I did my very, very best. I left it all on the field. I gave this every ounce of everything I had.

* The realization that you will, from that moment on, draw all your breaths through someone else’s lungs hits you harder when you aren’t prepared.

* Words matter. Be better.

* I want you to always remember that you can become whatever you want to become, but that’s nowhere near as important as knowing that you can be exactly who you are.

* I've done what I can to teach you to never feel threatened by strong women. I married the strongest one I've ever met.

* This parenthood thing didn’t come with instructions, that’s all I’m saying. You spit on the napkin. Then you wipe the child’s face with the napkin. You don’t spit straight onto the child. My bad.

* We want you to be better than us. Because if our kids don’t grow up to be better than us, then what’s the point of all this? We want you to be kinder, smarter, more humble, more generous, and more selfless than we are. We want to give you the very best circumstances we can possibly provide. So we follow sleeping methods and go to seminars and buy ergonomic bathtubs and push car-seat salesmen up against the wall and shout, ‘The safest! I want THE SAFEST, doyouhearme?!’ (Not that I’ve ever done that, of course; you shouldn’t pay so much attention to what your mother says.)

#### Pastoral Song: A Farmer's Journey, by James Rebanks
* The modern world worships the idea of the self, the individual, but it is a gilded cage: there is another kind of freedom in becoming absorbed in a little life on the land. In a noisy age, I think perhaps trying to live quietly might be a virtue. 

* There is something about planting trees that feels good. If you have done it well, it will outlast you and leave the world a little richer and more beautiful because of your efforts. Planting a tree means you believe in, and care about, a world that will be there after you are gone. It means you have thought about more than yourself, and that you can imagine a future beyond your own lifespan, and you care about that future.

* These people lived insular, often deeply private lives focused on their work. Their voices were rarely heard, because they sought no audience. Their identities were constructed from things that couldn’t be bought in shops. They wore old clothes and only went shopping occasionally for essentials. They held “shop-bought” things in great contempt. They preferred cash to credit, and would mend anything that broke, piling up old things to use again someday, rather than throwing them away. They had hobbies and interests that cost nothing, turning their necessary tasks, like catching rats or foxes, into sport. Their friendships were built around their work, and the breeds of cattle and sheep they kept. They rarely took holidays or bought new cars. And it wasn’t all work—a lot of time was spent on farm-related activities that were communal and more relaxed, or in the simple enjoyment of wild things. My grandfather called this way of life “living quietly.” 

* Thankfully, my father never sent me to agricultural college. He was old-school and thought those places turned out people who knew the cost of everything and the value of nothing.

* There were profoundly important questions about the potential effects of each new technology that it was nobody's job to ask or answer. There was no mechanism for farmers or ecologists to judge whether a technology or new farming practice was on balance a "good" thing or a "bad" thing, and we really didn't know when we had crossed the invisible threshold from one to the other.

#### Notes of a Native Son, by James Baldwin
* I don't like people who like me because I'm a Negro; neither do I like people who find in the same accident grounds for contempt. I love America more than any other country in the world, and, exactly for this reason, I insist on the right to criticize her perpetually. I think all theories are suspect, that the finest principles may have to be modified, or may even be pulverized by the demands of life, and that one must find, therefore, one's own moral center and move through the world hoping that this center will guide one aright. I consider that I have many responsibilities, but none greater than this: to last, as Hemingway says, and get my work done.

* I am what time, circumstance, history, have made of me, certainly, but I am, also, much more than that. So are we all.

* One writes out of one thing only--one's own experience. Everything depends on how relentlessly one forces from this experience the last drop, sweet or bitter, it can possibly give. This is the only real concern of the artist, to recreate out of the disorder of life that order which is art.

* I imagine that one of the reasons people cling to their hates so stubbornly is because they sense, once hate is gone, that they will be forced to deal with pain.

* You can not describe anything without betraying your point of view, your aspirations, your fears, your hopes. Everything.

* It was better not to judge the man who had gone down under an impossible burden. It was better to remember: Thou knowest this man's fall, but thou knowest not his wrassling.

#### The Fire This Time, edited by Jesmyn Ward
* You can't tiptoe toward justice. You can't walk up to the door all polite and knock once or twice, hoping someone's home. Justice is a door that, when closed, must be kicked in. (Daniel Jose Older)

* I want to look happily forward. I want to be optimistic. I want to have a dream. I want to live in jubilee. I want my daughters to feel that they have the power to at least try to change things, even in a world that resists change with more strength than they have. I want to tell them they can overcome everything, if the are courageous, resilient and brave. Paradoxically, I also want to tell them their crowns have already been bought and paid for and that all they have to do is put them on their heads. But the world keeps tripping me up. My certainty keeps flailing. (Edwidge Danticat)

* Though the white liberal imagination likes to feel temporarily bad about black suffering, there really is no mode of empathy that can replicate the daily strain of knowing that as a black person you can be killed for simply being black: no hands in your pockets, no playing music, no sudden movements, no driving your car, no walking at night, no walking in the day, no turning onto this street, no entering this building, no standing your ground, no standing here, no standing there, no talking back, no playing with toy guns, no living while black. (Jesmyn Ward)

#### Richard Wagemese Selected: What Comes from Spirit, by Richard Wagamese
* So I explained to him what the Old One had told me.
The process of braiding hair is like a prayer, he said. Each of the three strands in a single braid represents many things. In one instance they might represent faith, honesty and kindness. In another they might be mind, body and spirit, or love, respect and tolerance. The important thing, he explained, was that each strand be taken as representative of one essential human quality.
As the men, or the women, braided their hair they concentrated or meditated on those three qualities. Once the braid was completed the process was repeated on the other side.
Then as they walked through their day they had visible daily reminders of the human qualities they needed to carry through life with them.
The Old One said they had at least about twenty minutes out of their day when they focused themselves entirely on spiritual principles. In this way, the people they came in contact with were the direct beneficiaries of that inward process. So braids, he said, reflected the true nature of Aboriginal people.
They reflected a people who were humble enough to ask the Creator for help and guidance on a daily basis. They reflected truly human qualities within the people themselves: ideals they sought to live by. And they reflected a deep and abiding concern for the planet, for life, their people and themselves.
Each time you braid your hair, he told me, you become another in a long line of spiritually based people and your prayer joins the countless others that have been offered up to the Creator since time began. You become a part of a rich and vibrant tradition.
As the young boy listened I could see the same things going on in his face that must have gone on in my own. Suddenly, a braid became so much more than a hairstyle or a cultural signature. It became a connection to something internal as well as external - a signpost to identity, tradition and self-esteem. The words Indian, Native and Aboriginal took on new meaning and new impact.” 

#### The Baseball 100, by Joe Posnanski
* But Jackie Robinson was a man of faith. I do not just mean faith in God, though he was indeed a religious man. He also had extraordinary faith in himself and his destiny. He believed deeply that he was the one meant to cross baseball's color line. He believed deeply that God would not have led him down this path only to fail. That faith filled him with something more powerful that confidence. He knew that we would succeed because to do anything less would be unthinkable.

#### Under a White Sky: The Nature of the Future, by Elizabeth Kolbert
* I was struck, and not for the first time, by how much easier it is to ruin an ecosystem than to run one.

* The strongest argument for gene editing cane toads, house mice, and ship rats is also the simplest: what's the alternative? Rejecting such technologies as unnatural isn't going to bring nature back. The choice is not between what is and what was, but between what is and what will be, which, often enough, is nothing.

* Declining emissions and rising atmospheric concentrations point to a stubborn fact about carbon dioxide: once it’s in the air, it stays there. How long, exactly, is a complicated question; for all intents and purposes, though, CO2 emissions are cumulative. The comparison that’s often made is to a bathtub. So long as the tap is running, a stoppered tub will continue to fill. Turn the tap down, and the tub will still keep filling, just more slowly.

* Pissing in your pants will only keep you warm for so long.

* If control is the problem, then, by the logic of the Anthropocene, still more control must be the solution.

#### Why Fish Don't Exist: A Story of Loss, Love, and the Hidden Order of Life, by Lulu Miller
* The work of good science is to try to peer beyond the "convenient" lines we draw over nature. To peer beyond intuition, where something wilder lives. To know that in every organism at which you gaze, there is complexity you will never comprehend.

* When I give up the fish, I get, at long last, that thing I had been searching for: a mantra, a trick, a prescription for hope. I get the promise that there are good things in store. Not because I deserve them. Not because I worked for them. But because they are as much a part of Chaos as destruction and loss. Life, the flip side of death. Growth, of rot.

* I have come to believe that it is our life's work to tear down this order, to keep tugging at it, trying to unravel it, to set free the organisms trapped underneath. That it is our life's work work to mistrust our measures. Especially those about moral and mental standing. To remember that behind every ruler there is a Ruler. To remember that a category is at best a proxy; at worst, a shackle.

* It was the dandelion principle! To some people a dandelion might look like a weed, but to others that same plant can be so much more. To an herbalist, it’s a medicine—a way of detoxifying the liver, clearing the skin, and strengthening the eyes. To a painter, it’s a pigment; to a hippie, a crown; a child, a wish. To a butterfly, it’s sustenance; to a bee, a mating bed; to an ant, one point in a vast olfactory atlas.

* Ignorance is the most delightful science in the world because it is acquired without labor or pains and keeps the mind from melancholy.

* This was what Darwin was trying so hard to get his readers to see: that there is never just one way of ranking nature's organisms. To get stuck on a single hierarchy is to miss the bigger picture, the messy truth of nature, the "whole machinery of life." The work of good science is to try and peer beyond the "convenient" lines we draw over nature. To peer beyond intuition where something wilder lives. To know that in every organism at which you gaze, there is complexity you will never comprehend.

* Slowly, it came into focus. This small web of people keeping one another afloat. All these minuscule interactions- a friendly wave, a pencil sketch, some plastic beads strung up a nylon cord- they might not look like much from the outside, but for the people caught inside that web? They might be everything, the very tethers that keep one bound to this planet.

#### Blood in the Water: The Attica Prison Uprising of 1971 and its Legacy, by Heather Ann Thompson
* So obvious was the racial discrimination at Attica that white prisoners readily agreed that guards applied rules differently to blacks and Puerto Ricans.

* I think Attica brings to mind several things. The first is the basic inhumanity of man to man, the veneer of civilization as we sit here today in a well-lit, reasonably well appointed room with suits and ties on objectively performing an autopsy on this day, yet cannot get at the absolute horror of the situation, to people, be they black, yellow, orange, spotted, whatever, whatever uniform they wore, that day tore from them the shreds of their humanity. The veneer was penetrated. After seeing that day I went home and sat down and spoke with my wife and I said for the first time being a somewhat dedicated amateur army type, I could understand what may have happened at My Lai.

* Ultimately, the human cost of the retaking was staggeringly high: 128 men were shot—some of them multiple times.75 Less than half an hour after the retaking had commenced, nine hostages were dead and at least one additional hostage was close to death. Twenty-nine prisoners had been fatally shot.

* A number of prisoners killed had, according to several witnesses, actually still been alive after troopers had control of the facility. 

* Even though only 37 percent of the prisoner population was white, whites held 74 percent of the jobs in Attica’s power house, 67 percent of the coveted clerk positions, and 62 percent of the staff jobs in the officers’ mess hall. By contrast, 76 percent of the men in the dreaded and low-paid metal shop, and 80 percent in the grueling grading companies, were African American or Puerto Rican.

#### Finding the Mother Tree: Discovering the Wisdom of the Forest, by Suzanne Simard
* This Mother Tree was the central hub that the saplings and seedlings nested around, with threads of different fungal species, of different colors and weights, linking them, layer upon layer, in a strong, complex web

* Such a marvel, the tenacity of the buds to surge with life every spring, to greet the lengthening days and warming weather with exuberance, no matter what hardships were brought by winter.

* Plants are attuned to one another's strengths and weaknesses, elegantly giving and taking to attain exquisite balance. There is grace in complexity, in actions cohering, in sum totals.

* I don’t presume to grasp Aboriginal knowledge fully. It comes from a way of knowing the earth—an epistemology—different from that of my own culture. It speaks of being attuned to the blooming of the bitterroot, the running of the salmon, the cycles of the moon. Of knowing that we are tied to the land—the trees and animals and soil and water—and to one another, and that we have a responsibility to care for these connections and resources, ensuring the sustainability of these ecosystems for future generations and to honor those who came before. Of treading lightly, taking only what gifts we need, and giving back. Of showing humility toward and tolerance for all we are connected to in this circle of life. But what my years in the forestry profession have also shown me is that too many decision-makers dismiss this way of viewing nature and rely only on select parts of science. The impact has become too devastating to ignore. We can compare the condition of the land where it has been torn apart, each resource treated in isolation from the rest, to where it has been cared for according to the Secwepemc principal of k̓wseltktnews (translated as “we are all related”) or the Salish concept of nə́c̓aʔmat ct (“we are one”). We must heed the answers we’re being given.

#### The Anthropocene Reviewed, by John Green
* 'In this world, you must be oh so smart, or oh so pleasant.’ Well, for years I was smart. I recommend pleasant.

* We can talk and talk and talk about what the pain is like, but we can never manage to convey what it is.

* We all know how loving ends. But I want to fall in love with the world anyway, to let it crack me open. I want to feel what there is to feel while I am here.

* One of the strange things about adulthood is that you are your current self, but you are also all the selves you used to be, the ones you grew out of but can't ever quite get rid of.

* To fall in love with the world isn’t to ignore or overlook suffering, both human or otherwise. For me anyway, to fall in love with the world is to look up at the night sky and feel your mind swim before the beauty and the distance of the stars. It is to hold your children while they cry and watch the sycamore trees leaf out in June. When my breastbone starts to hurt, and my throat tightens and tears well in my eyes, I want to look away from feeling. I want to deflect with irony or anything else that will keep me from feeling directly. We all know how loving ends. But I want to fall in love with the world anyway, to let it crack me open. I want to feel what there is to feel while I am here.

* You can't see the future coming--not the terrors, for sure, but you also can't see the wonders that are coming, the moments of light-soaked joy that await each of us.

* I'll never again speak to many of the people who loved me into this moment, just as you will never speak to many of the people who loved you into your now. So we raise a glass to them--and hope that perhaps somewhere, they are raising a glass to us.

* When people we love are suffering, we want to make it better. But sometimes - often, in fact - you can't make it better. I'm reminded of something my supervisor said to me when I was a student chaplain: "Don't just do something. Stand there."

#### All Our Relations: Finding the Path Forward, by Tanya Talaga
* In Ojibwe and Cree culture, leadership didn't mean power; it meant caring.

* I don't want to talk about reconciliation. I want to talk about rights.

* If you are conditioned not to care, you are conditioned to indifference, and there is a violence to that indifference.

#### Bird by Bird: Some Instructions on Writing and Life, by Anne Lamott
* Thirty years ago my older brother, who was ten years old at the time, was trying to get a report written on birds that he'd had three months to write, which was due the next day. We were out at our family cabin in Bolinas, and he was at the kitchen table close to tears, surrounded by binder paper and pencils and unopened books about birds, immobilized by the hugeness of the task ahead. Then my father sat down beside him put his arm around my brother's shoulder, and said, "Bird by bird, buddy. Just take it bird by bird.” 

* For some of us, books are as important as almost anything else on earth. What a miracle it is that out of these small, flat, rigid squares of paper unfolds world after world after world, worlds that sing to you, comfort and quiet or excite you. Books help us understand who we are and how we are to behave. They show us what community and friendship mean; they show us how to live and die.

* Perfectionism is the voice of the oppressor, the enemy of the people. It will keep you cramped and insane your whole life, and it is the main obstacle between you and a shitty first draft. I think perfectionism is based on the obsessive belief that if you run carefully enough, hitting each stepping-stone just right, you won't have to die. The truth is that you will die anyway and that a lot of people who aren't even looking at their feet are going to do a whole lot better than you, and have a lot more fun while they're doing it.

* You own everything that happened to you. Tell your stories. If people wanted you to write warmly about them, they should have behaved better.

* Writing and reading decrease our sense of isolation. They deepen and widen and expand our sense of life: they feed the soul. When writers make us shake our heads with the exactness of their prose and their truths, and even make us laugh about ourselves or life, our buoyancy is restored. We are given a shot at dancing with, or at least clapping along with, the absurdity of life, instead of being squashed by it over and over again. It's like singing on a boat during a terrible storm at sea. You can't stop the raging storm, but singing can change the hearts and spirits of the people who are together on that ship.

* E.L. Doctorow said once said that 'Writing a novel is like driving a car at night. You can see only as far as your headlights, but you can make the whole trip that way.' You don't have to see where you're going, you don't have to see your destination or everything you will pass along the way. You just have to see two or three feet ahead of you. This is right up there with the best advice on writing, or life, I have ever heard.

* Clutter and mess show us that life is being lived...Tidiness makes me think of held breath, of suspended animation... Perfectionism is a mean, frozen form of idealism, while messes are the artist's true friend. What people somehow forgot to mention when we were children was that we need to make messes in order to find out who we are and why we are here.

#### All the White Friends I Couldn't Keep: Hope—And Hard Pills to Swallow—About Fighting for Black Lives, by Andre Henry
* This might explain why white people are so defensive about their space. They'll insist at their dinner tables are not political. And while it may be true that they do no intentional political consciousness-raising at Sunday lunch, they nevertheless uphold and protect the dominant and pervasive anti-Black common sense of the wider society while they eat. Then they reinterpret our Black-experiences--which undermine the myths they crave--as "politics," a euphemism for impolite conversation. They gaslight us and call it keeping the peace.

* Black America has watched this pattern of outrage management about Black suffering for years. We’ve seen police plant weapons on their victims, as they did in the case of Walter Scott (cover up). Media outlets tell us drugs were in someone’s system when the police murdered them, as they did with George Floyd (devalue). White people constantly try to reframe police brutality as a problem of “a few bad apples” instead of a systemic problem (reinterpret). When the grand jury refused to indict Darren Wilson for the killing of Michael Brown, that became the end of the story for eager racism deniers, though the report also showed racial bias in the conduct of the Ferguson police department (use official channels). And there isn’t room for a full list of the times protesters of these injustices were met in the streets with flash-bang grenades and tanks (intimidate). Oppressors have perfected these tactics so well, they stop revolutions before they start, on a daily basis, without us ever noticing. Rank-and-file white people also try to stamp out Black rage wherever it emerges. They tell us Black anger is destructive and can’t be trusted. The truth is just the opposite. Black rage is trustworthy because it carries an analysis of present injustices. On a physiological level, anger is the body’s way of telling us that a boundary has been violated. It’s the natural emotional response humans have to being wronged, especially if that wrong is recurring and denied by the harmdoers. Therefore, Black rage is a healthy sign that we as a people recognize the crimes that have been, and continue to be, committed against us. Our anger is based in our personal experiences of anti-Black hostility in the white world and backed by our knowledge of our history.

#### How To Be Perfect: The Correct Answer to Every Moral Question, by Michael Schur
* What are we doing? Why are we doing it? Is there something we could do that’s better? Why is it better?

* True happiness comes from remaining focused on the things we do, and doing them with no purpose other than to do them.

* A person is a person through other people.

* This habituation, the practice of working at our virtues, is really the whole shebang here.

* In those rare times when you have to make a decision and you assemble the pieces in exactly the right way, so the image of what to do comes sharply into focus—you will feel alive and fulfilled and elated. You will feel like you’re flourishing.

* The most important part of becoming better people, I’ll say yet again, is that we care about whether what we do is good or bad, and therefore try to do the right thing. If we love a problematic person or thing too much to part with it altogether, I think that means we have to keep two ideas in our head at the same time: I love this thing. The person who made it is troubling.

* These moments—when we are caught in a situation that has no clear answer, no heuristic to employ that will spit out a theoretical but practically impossible “correct” decision—are when we see the true value in failure. We’re deciding to do something that will, someday, backfire. The more we chew on it and work it through, the more meaning we can derive from that backfire when it happens.

#### Meander, Spiral, Explode: Design and Pattern in Narrative, by Jane Alison
* So often fictions that experiment formally do so at the expense of feeling. They toy on surfaces or are purely cerebral affairs, don’t explore human complexities. But the mostly unconventional narratives I’ve been discussing have dealt powerfully with core human matters. … And they have found patterns other than the wave to do this, or worked in a doubled, moiré relation with the wave, one pattern upon another. I believe they’ve done this organically: a meander or net or explosion was simply the pattern the material needed.

* Even arcing fictions can be designed, with texture, color, symmetry, or repetitions graphable as wavelike stripes.

#### People Love Dead Jews: Reports from a Haunted Present, by Dara Horn
* The line most often quoted from Frank’s diary are her famous words, “I still believe, in spite of everything, that people are truly good at heart.” These words are “inspiring,” by which we mean that they flatter us. They make us feel forgiven for those lapses of our civilization that allow for piles of murdered girls—and if those words came from a murdered girl, well, then, we must be absolved, because they must be true. That gift of grace and absolution from a murdered Jew (exactly the gift that lies at the heart of Christianity) is what millions of people are so eager to find in Frank’s hiding place, in her writings, in her “legacy.” It is far more gratifying to believe that an innocent dead girl has offered us grace than to recognize the obvious: Frank wrote about people being “truly good at heart” before meeting people who weren’t. Three weeks after writing those words, she met people who weren’t.

* The freedoms that we cherish are meaningless without our commitments to one another: to civil discourse, to actively educating the next generation, to welcoming strangers, to loving our neighbors. The beginning of freedom is the beginning of responsibility. Our night of vigil has already begun.

* Since ancient times, in every place they have ever lived, Jews have represented the frightening prospect of freedom. As long as Jews existed in any society, there was evidence that it in fact wasn't necessary to believe what everyone else believed, that those who disagreed with their neighbors could survive and even flourish against all odds. The Jews' continued distinctiveness, despite overwhelming pressure to become like everyone else, demonstrated their enormous effort to cultivate that freedom: devotion to law and story, deep literacy, and an absolute obsessiveness about consciously transmitting those values between generations. The existence of Jews in any society is a reminder that freedom is possible, but only with responsibility—and that freedom without responsibility is no freedom at all.

* The insane conspiracy theories that motivate people who commit antisemitic violence reflect a fear of real freedom: a fondness for tyrants, an aversion to ideas unlike their own, and most of all, a casting-off of responsibility for complicated problems. None of this is a coincidence.

* These stories, I came to understand, were presenting a challenge to the Western idea of the purpose of creativity. Stories with definitive endings don’t necessarily reflect a belief that the world makes sense, but they do reflect a belief in the power of art to make sense of it. What one finds in Jewish storytelling, though, is something really different: a kind of realism that comes from humility, from the knowledge that one cannot be true to the human experience while pretending to make sense of the world.

#### Patriarchy Blues: Reflections on Manhood, by Frederick Joseph
* You are more than the trauma you have endured, and you can be more than the trauma you have caused.

* My love grows daily for the man I am trying to be....

* I hope that my experiences, my pain, my growth serve as reminders that we are not bound to the gravity of pain. We are not bound to misogyny, homophobia, transphobia, or any manifestation of what has kept us from the ultimate joy of freedom.

* Realizing your life won't last forever has a way of reminding you to be free. Realizing your name may last forever has a way of reminding you to help free others.

* Many view this concept as altruistic. But in order for any of us to be free, we must no longer view the oppressions of other people as problems specific to individual groups, but instead understand that oppression in any form decays the very fabric of our society.

#### Craft in the Real World: Rethinking Fiction Writing and Workshopping, by Matthew Salesses
* Realism insists on one representation of what is real. Not only through what is narrated on the page, but through the shape that narration takes.

* For a marginalized writer writing to a normative audience, the writer has to be wary of normative craft. Much of what we learn about craft (about the expectations we are supposed to consider) implies a straight, white, cis, able (etc.) audience. It is easy to forget who we are writing for if we do not keep it a conscious consideration, and the default is not universal, but privileged.

* Make no mistake—writing is power. What this fact should prompt us to ask is: What kind of power is it, where does it come from, and what does it mean?

* Craft is the history of which kind of stories have typically held power—and for whom—so it also is the history of which stories have typically been omitted.

#### The Explosive Child: A New Approach for Understanding and Parenting Easily Frustrated, Chronically Inflexible Children, by Ross W. Greene
* When your child has the skills to respond adaptively to demands and expectations, he does. If your child had the skills to handle disagreements and changes in plan and adults setting limits and demands being placed on him without falling apart, he’d be handling these challenges adaptively. Because he doesn’t have those skills, he isn’t. But let there be no doubt: he’d prefer to be handling those challenges adaptively because **doing well is preferable.** And because—and this is, without question, the most important theme of this entire book— **kids do well if they can.** 

* We all want our own way; some of us have the skills to get our own way adaptively, and some of us don’t.

* Behaviorally challenging kids are challenging because they’re lacking the skills to not be challenging.

* An explosive outburst—like other forms of maladaptive behavior—occurs when the cognitive demands being placed upon a person outstrip that person’s capacity to respond adaptively.

* Diagnoses —such as ADHD, oppositional defiant disorder, bipolar disorder, depression, an autism spectrum disorder, reactive attachment disorder, the newly coined disruptive mood regulation disorder, or any other disorder—can be helpful in some ways. They “validate” that there’s something different about your kid, for example. But they can also be counterproductive in that they can cause caregivers to focus more on a child’s challenging behaviors rather than on the lagging skills and unsolved problems giving rise to those behaviors. Also, diagnoses suggest that the problem resides within the child and that it’s the child who needs to be fixed. The reality is that it takes two to tango. Let there be no doubt, there’s something different about your child. But you are part of the mix as well. How you understand and respond to the hand you’ve been dealt is essential to helping your child.

* Your energy can be devoted far more productively to collaborating with your child on solutions to the problems that are causing challenging episodes than in sticking with strategies that may actually have made things worse and haven’t led to durable improvement.

* The reason reward and punishment strategies haven’t helped is because they won’t teach your child the skills he’s lacking or solve the problems that are contributing to challenging episodes.

#### Cribsheet: A Data-Driven Guide to Better, More Relaxed Parenting, from Birth to Preschool, by Emily Oster
* First, recognize that children are not adults, and you usually cannot improve their behavior with a discussion. If your four-year-old is taking their shirt off in the museum, they will not respond to a reasoned discussion about how you actually do need to wear a shirt in public places. The flip side of this - more important - is that you shouldn't expect them to respond to adult reasoning. And as a result, you should not get angry the way you would if, say, your spouse was stripping in the museum and didn't stop after you explained why they shouldn't. Toddler discipline is, really, parental discipline. Breathe. Take a second.

* If you want to collect data and make pretty graphs, go for it. But remember that this is the illusion of control, not actual control.

* So, yes, it makes sense to take parenting seriously, and to want to make the best choices for your kid and the best choices for you. But there will be many times that you need to just trust that if you’re doing your best, that’s all you can do. Being present and happy with your kids is more important than, say, worrying about bees. At the end, let’s raise a glass to using data where it’s useful, to making the right decisions for our families, to doing our best, and—sometimes—to just trying not to think about it.

* Your choices can be right for you but also not necessarily the best choices for other people. Why? You are not other people. Your circumstances differ. Your preferences differ. In the language of economics, your constraints differ. 

#### When We Cease to Understand the World, by Benjamin Labatut
* We can pull atoms apart, peer back at the first light and predict the end of the universe with just a handful of equations, squiggly lines and arcane symbols that normal people cannot fathom, even though they hold sway over their lives. But it's not just regular folks; even scientists no longer comprehend the world. Take quantum mechanics, the crown jewel of our species, the most accurate, far-ranging and beautiful of all our physical theories. It lies behind the supremacy of our smartphones, behind the Internet, behind the coming promise of godlike computing power. It has completely reshaped our world. We know how to use it, it works as if by some strange miracle, and yet there is not a human soul, alive or dead, who actually gets it. The mind cannot come to grips with its paradoxes and contradictions. It's as if the theory had fallen to earth from another planet, and we simply scamper around it like apes, toying and playing with it, but with no true understanding.

* He had also gone through a bad divorce, become estranged from his only daughter and been diagnosed with skin cancer, but he insisted that all of that, however painful, was secondary to the sudden realization that it was mathematics—not nuclear weapons, computers, biological warfare or our climate Armageddon—which was changing our world to the point where, in a couple of decades at most, we would simply not be able to grasp what being human really meant.

* Looking at the waves scudding outwards and getting lost on the horizon, he could not help but recall the words of his mentor, the Danish physicist Niels Bohr, who had once told him that a part of eternity lies in reach of those capable of staring, unblinking, at the sea’s deranging expanses.

* Heisenberg’s uncertainty principle shredded the hopes of all those who had put their faith in the clockwork universe Newtonian physics had promised.

#### Known My Name, by Chanel Miller
* I survived because I remained soft, because I listened, because I wrote. Because I huddled close to my truth, protected it like a tiny flame in a terrible storm. Hold up your head when the tears come, when you are mocked, insulted, questioned, threatened, when they tell you you are nothing, when your body is reduced to openings. The journey will be longer than you imagined, trauma will find you again and again. Do not become the ones who hurt you. Stay tender with your power. Never fight to injure, fight to uplift. Fight because you know that in this life, you deserve safety, joy, and freedom. Fight because it is your life. Not anyone else’s. I did it, I am here. Looking back, all the ones who doubted or hurt or nearly conquered me faded away, and I am the only one standing. So now, the time has come. I dust myself off, and go on.

* My pain was never more valuable than his potential.

* Most of us understand that your future is not promised to you. It is constructed day by day, through the choices you make. Your future is earned, little by little, through hard work and action. If you don’t act accordingly, that dream dissolves.

* I used to shrink at harsh tones, used to be afraid. Until I learned it takes nothing to be hostile. Nothing. It is easy to be the one yelling, chucking words that burn like coals, neon red, meant to harm. I have learned I am water. The coals sizzle, extinguishing when they reach me. I see how, those fiery coals are just black stones, sinking to the bottom.

#### Drawdown: The Most Comprehensive Plan Ever Proposed to Reverse Global Warming, by Paul Hawken
* We see global warming not as an inevitability but as an invitation to build, innovate, and effect change, a pathway that awakens creativity, compassion, and genius. This is not a liberal agenda, nor is it a conservative one. This is the human agenda.

* The act I want to talk about is growing some—even just a little—of your own food. Rip out your lawn, if you have one, and if you don’t—if you live in a high-rise, or have a yard shrouded in shade—look into getting a plot in a community garden. Measured against the Problem We Face, planting a garden sounds pretty benign, I know, but in fact it’s one of the most powerful things an individual can do—to reduce your carbon footprint, sure, but more important, to reduce your sense of dependence and dividedness: to change the cheap-energy mind.

* No other mechanism known to humankind is as effective in addressing global warming as capturing carbon dioxide from the air through photosynthesis.

#### The Invisible Kingdom: Reimagining Chronic Illness, by Meghan O'Rourke
* I know many people who are suspicious of diagnoses—they think of them as labels that reduce or stigmatize. I knew, already, that a diagnosis was not going to answer all my questions. But I craved a diagnosis because it is a form of understanding.

* And so it is a truth universally acknowledged that a young woman in possession of vague symptoms like fatigue and pain will be in search of a doctor who believes she is actually sick.

* But the fatigue of physical dysfunction, I came to recognize, is as different from normal sleep deprivation as COVID-19 is from the common cold. It was not caused by needing sleep, I thought, but by my body’s cellular conviction that it needed to conserve energy in order to fix whatever was wrong. The feeling erased my will, the sense of identity that drives most of us. The worst part of my fatigue was the loss of an intact sense of self.

* There is a razor-thin line between trying to find something usefully redemptive in illness and lying to ourselves about the nature of suffering. Until we mourn what is lost in illness—and until we have a medical community that takes seriously the suffering of patients—we should not celebrate what is gained in it.

* There is a razor-thin line between trying to find something usefully redemptive in illness and lying to ourselves about the nature of suffering. Until we mourn what is lost in illness—and until we have a medical community that takes seriously the suffering of patients—we should not celebrate what is gained in it.

#### Gathering Moss: A Natural and Cultural History of Mosses, by Robin Wall Kimmerer
* Mosses are so little known by the general public that only a few have been given common names. Most are known solely by their scientific Latin names, a fact which discourages most people from attempting to identify them. But I like the scientific names, because they are as beautiful and intricate as the plants they name. Indulge yourself in the words, rhythmic and musical, rolling off your tongue: Dolicathecia striatella, Thuidium delicatulum, Barbula fallax.

* There is an ancient conversation going on between mosses and rocks, poetry to be sure. About light and shadow and the drift of continents. This is what has been called the "dialect of moss on stone" - an interface of immensity and minute ness, of past and present, softness and hardness, stillness and vibrancy, yin and yan.

* Just as you can pick out the voice of a loved one in the tumult of a noisy room, or spot your child's smile in a sea of faces, intimate connection allows recognition in an all-too-often anonymous world. This sense of connection arises from a special kind of discrimination, a search image that comes from a long time spent looking and listening. Intimacy gives us a different way of seeing, when visual acuity is not enough.

* In indigenous ways of knowing, it is understood that each living being has a particular role to play. Every being is endowed with certain gifts, its own intelligence, its own spirit, its own story. Our stories tell us that the Creator gave these to us, as original instructions. The foundation of education is to discover that gift within us and learn to use it well.

* I am trying to understand what it means to own a thing, especially a wild and living being. To have exclusive rights to its fate? To dispose of it at will? To deny others it’s use? Ownership seems a uniquely human behavior, a social contract validating the desire for purposeless possession and control.

* Infrared satellite imagery, optical telescopes, and the Hubbell space telescope bring vastness within our visual sphere. Electron microscopes let us wander the remote universe of our own cells. But at the middle scale, that of the unaided eye, our senses seem to be strangely dulled. With sophisticated technology, we strive to see what is beyond us, but are often blind to the myriad sparkling facets that lie so close at hand. We thing we're seeing when we've only scratched the surface. Our acuity at this middle scale seems diminished, not by any failing of the eyes, but by the willingness of the mind. Has the power of our devices led us to distrust our unaided eyes? Or have we become dismissive of what takes no technology but only time and patience to perceive? Attentiveness alone can rival the most powerful magnifying lens.

#### The Song of the Cell: An Exploration of Medicine and the New Human, by Siddhartha Mukherjee
* Life’s definition, as it stands now, is akin to a menu. It is not one thing but a series of things, a set of behaviors, a series of processes, not a single property. To be living, an organism must have the capacity to reproduce, to grow, to metabolize, to adapt to stimuli, and to maintain its internal milieu.

* Cell biology is inextricably linked with genetics, pathology, epidemiology, epistemology, taxonomy, and anthropology.

* Synaptic pruning is thought to sharpen and reinforce the 'correct' synapses, while removing the weak and unnecessary ones. 'It reinforces an old intuition,' a psychiatrist in Boston told me. 'The secret of learning is the systematic elimination of excess. We grow, mostly, by dying." We are hardwired not to be hardwired, and this anatomical plasticity may be the key to the plasticity of our minds.

#### Eager: The Surprising Secret Life of Beavers and Why They Matter, by Ben Goldfarb
* Beavers, the animal that doubles as an ecosystem, are ecological and hydrological Swiss Army knives, capable, in the right circumstances, of tackling just about any landscape-scale problem you might confront. Trying to mitigate floods or improve water quality? There’s a beaver for that. Hoping to capture more water for agriculture in the face of climate change? Add a beaver. Concerned about sedimentation, salmon populations, wildfire? Take two families of beaver and check back in a year. If that all sounds hyperbolic to you, well, I’m going to spend this book trying to change your mind.

* Yet beavers are as balletic in water as they are clumsy out of it. They can hold their breath for up to fifteen minutes, and their underwater gymnastics are powered by webbed hind feet. Transparent eyelids allow them to see below the surface, while a second set of fur-lined lips close behind their teeth, permitting them to chew and drag wood without drowning. Building dams expands the extent of beavers’ watery domains, submerges lodge entrances to repel predators, and gives them a place to stash their food caches. Ponds also serve to irrigate water-loving trees like willow, allowing beavers to operate as rotational farmers: They’ll chew down vegetation in one corner of their compound while cultivating their next crop in another.

* Add up all those dependents, and you begin to comprehend why scientists consider beavers the ultimate keystone species. To architects, a keystone is the wedge-shaped block that forms the apex of a stone arch, the brick that holds the span in place. To ecologists, a keystone species is that rare organism that likewise supports an entire biological community. Salmon, whose decomposing carcasses sustain grizzly bears, eagles, and even trees, are one keystone species; elephants, who clear the savanna for grasses by uprooting trees and shrubs, are another. Pull the keystone out, and the arch—or the ecosystem—collapses.

#### H is for Hawk, by Helen Macdonald
* There is a time in life when you expect the world to be always full of new things. And then comes a day when you realise that is not how it will be at all. You see that life will become a thing made of holes. Absences. Losses. Things that were there and are no longer. And you realise, too, that you have to grow around and between the gaps, though you can put your hand out to where things were and feel that tense, shining dullness of the space where the memories are.

* We carry the lives we've imagined as we carry the lives we have, and sometimes a reckoning comes of all the lives we have lost.

* Here’s a word. Bereavement. Or, Bereaved. Bereft. It’s from the Old English bereafian, meaning ‘to deprive of, take away, seize, rob’. Robbed. Seized. It happens to everyone. But you feel it alone. Shocking loss isn’t to be shared, no matter how hard you try.

* The archaeology of grief is not ordered. It is more like earth under a spade, turning up things you had forgotten. Surprising things come to light: not simply memories, but states of mind, emotions, older ways of seeing the world.

* Some things happen only once, twice in a lifetime. The world is full of signs and wonders that come, and go, and if you are lucky you might be alive to see them.

* What happens to the mind after bereavement makes no sense until later. Even as I watched I’d half-realised Prideaux was a figure I’d picked out for a father. But what I should have realised, too, on those northern roads, is that what the mind does after losing one’s father isn’t just to pick new fathers from the world, but pick new selves to love them with.

* Being a novice is safe. When you are learning how to do something, you do not have to worry about whether or not you are good at it. But when you have done something, have learned how to do it, you are not safe any more. Being an expert opens you up to judgement.

#### Laughing with the Trickster, by Tomson Highway
* As for all the languages the whole world over, they are so different one from the other that the result, if they were spoken all at once, would be a cacophony, a dreadful clattering of wayward consonants. Still, all are here for a reason. Each has its genius, its strength, its applicability. Most pointedly, if botanists tell us that the Amazon jungle has plants and herbs that number in the millions, each of which holds the key to a possible cure for physical ailments, illness, and disease, then languages function likewise. The difference is that the ailments they address are not so much physical as emotional, psychological, and spiritual, ailments that can be just as debilitating, just as lethal.

## 2023 Reads {.tabset .tabset-pills}
### Fiction
#### Foster, by Claire Keegan
* 'You don’t ever have to say anything,’ he says. ‘Always remember that as a thing you need never do. Many’s the man lost much just because he missed a perfect opportunity to say nothing.'

* Neither one of us talks, the way people sometimes don’t when they are happy – but as soon as I have this thought, I realise its opposite is also true.

#### Land of Big Numbers, by Te-Ping Chen
* She laughed a lot, and easily. It wasn't until we actually became friends that I realized she was often very sad. America is like that, I must say, free and easy until you know better.

* They were fond of each other, and that was more than you could say about most marriages.

* A great wasteland of sorrow was opening up in him, unfolding dozens of tiny shacks, terrible squatters setting up residence, banging their miniature liquor bottles against his chest, a hundred feet trampling his organs.

### Non-Fiction
#### The Dawn of Everything, by David Graeber & David Wengrow
* We are projects of collective self-creation. What if we approached human history that way? What if we treat people, from the beginning, as imaginative, intelligent, playful creatures who deserve to be understood as such? What if, instead of telling a story about how our species fell from some idyllic state of equality, we ask how we came to be trapped in such tight conceptual shackles that we can no longer even imagine the possibility of reinventing ourselves?

* That indigenous Americans lived in generally free societies, and that Europeans did not, was never really a matter of debate in these exchanges: both sides agreed this was the case.

* If human beings, through most of our history, have moved back and forth fluidly between different social arrangements, assembling and dismantling hierarchies on a regular basis, maybe the real question should be ‘how did we get stuck?’ How did we end up in one single mode? How did we lose that political self-consciousness, once so typical of our species? How did we come to treat eminence and subservience not as temporary expedients, or even the pomp and circumstance of some kind of grand seasonal theatre, but as inescapable elements of the human condition? If we started out just playing games, at what point did we forget that we were playing?

* We will suggest that there is a reason why so many key Enlightenment thinkers insisted that their ideals of individual liberty and political equality were inspired by Native American sources and examples. Because it was true.

* Fascination with the question of social inequality was relatively new in the 1700s, and it had everything to do with the shock and confusion that followed Europe’s sudden integration into a global economy, where it had long been a very minor player.

* Kandiaronk: I have spent six years reflecting on the state of European society and I still can’t think of a single way they act that’s not inhuman, and I genuinely think this can only be the case, as long as you stick to your distinctions of ‘mine’ and ‘thine’. I affirm that what you call money is the devil of devils; the tyrant of the French, the source of all evils; the bane of souls and slaughterhouse of the living. To imagine one can live in the country of money and preserve one’s soul is like imagining one could preserve one’s life at the bottom of a lake. Money is the father of luxury, lasciviousness, intrigues, trickery, lies, betrayal, insincerity, – of all the world’s worst behaviour. Fathers sell their children, husbands their wives, wives betray their husbands, brothers kill each other, friends are false, and all because of money. In the light of all this, tell me that we Wendat are not right in refusing to touch, or so much as to look at silver?

#### How to Keep House While Drowning, by K.C. Davis
* ...the key to juggling is to know that some of the balls you have in the air are made of plastic & some are made of glass.

* No one ever shamed themselves into better mental health.

* If I viewed a day of screen time and not doing any scheduled care tasks as a failure, it would be a lot harder to “get back into routine.” But I didn’t. Trolls and pj’s day was a day when we were being gentle with ourselves, allowing ourselves to take it easy and rest—a day of kindness. Framing it as kindness instead of failure was the key to being able to wake up and choose to get things done the next day.

#### Good Inside: A Guide to Becoming the Parent You Want to Be, by Becky Kennedy
* As a parent, I challenge myself to sit with my child in his feeling of distress so he knows he isn’t alone, as opposed to pulling my child out of this moment, which leaves him alone the next time he finds himself there.

* ...if I look for perfect, I’ll miss growth . . . and I’m a pretty big fan of growth.

* Building resilience is about developing the capacity to tolerate distress, to stay in and with a tough, challenging moment, to find our footing and our goodness even when we don’t have confirmation of achievement or pending success.

* As a result, many parents see behavior as the measure of who our kids are, rather than using behavior as a clue to what our kids might need.
